CREATE DATABASE IF NOT EXISTS movemind_db;

USE movemind_db;

CREATE TABLE User(
id INT AUTO_INCREMENT PRIMARY KEY,
firstname  VARCHAR(50) NOT NULL,
lastname   VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE ,
password_hash VARCHAR(255) NOT NULL,
creation_datetime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
INDEX idx_email(email));
